apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-client
  template:
    metadata:
      labels:
        app: greeter-client
    spec:
      containers:
        - name: greeter-client
          image: greeter-client:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: greeter-client
spec:
  selector:
    app: greeter-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer