apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      labels:
        app: greeter-server
    spec:
      containers:
        - name: greeter-server
          image: greeter-server:1.0
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: greeter-server
spec:
  selector:
    app: greeter-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090