spring.application.name: "greeter-client"
server.port: 8080
grpc.server.port: 9091
grpc:
  client:
    greeter-service:
      address: "static://localhost:9090"
      enableKeepAlive: true
      negotiationType: plaintext